### ISSUE TITLE
Add a 'copy' deployment mode for cargo-screeps

### ISSUE THREAD

**Issue by jechase** [daboross/screeps-in-rust-via-wasm#11]
I often find myself wanting to deploy to a local sandbox server that I'm running, and sometimes can't be bothered to set up the authentication mod that allows for the http upload functionality to work.

It would be nice to have an option to instead have the build artifacts copied to the directory that the screeps client watches and uploads for you.

The config could be something like:

```toml
mode = "copy" # Default: copy, valid: copy|upload
branch = "default"

[upload]
username = "user"
password = "pass"
# optional:
# ptr = false
# hostname = "localhost"
# ssl = true
# port = 443

[copy]
dest = "/path/to/screeps/client/scripts" # path to directory containing the branch 
                                         # directories, configured branch should be
                                         # appended
prune = true # whether or not to clear the destination of extra files
```

Edit: This is probably something that I'd be willing to work on myself.
